#!/bin/sh -e

usage(){
    echo "Usage: $(basename $0) (amd64|i386|arm64|armhf)"
    exit 1
}

if [ -z "$1" ]; then
    usage
fi

BUILD=build
version=$(cat VERSION)
architecture=$1
default_key=$(grep "var secretKey" main.go | cut -c24-85)
echo Default key: "$default_key"
secret_key=$(cat secret)
echo Secret key: "$secret_key"

rm -Rf ${BUILD}
mkdir -p ${BUILD}/release ${BUILD}/tmp
cp -R deb/* ${BUILD}/tmp

echo "Building version $version..."

cp main.go main.go~
sed -i "s/${default_key}/${secret_key}/g" main.go
grep "var secretKey" main.go | cut -c24-85

go get github.com/leaanthony/mewn/cmd/mewn

case ${architecture} in
    amd64)
        GOOS=linux GOARCH=amd64 mewn build -o ${BUILD}/tmp/usr/bin/delauncher main.go
        ;;
    i386)
        GOOS=linux GOARCH=386 mewn build -o ${BUILD}/tmp/usr/bin/delauncher main.go
        ;;
    arm64)
        GOOS=linux GOARCH=arm64 GOARM=7 mewn build -o ${BUILD}/tmp/usr/bin/delauncher main.go
        ;;
    armhf)
        GOOS=linux GOARCH=arm GOARM=7 mewn build -o ${BUILD}/tmp/usr/bin/delauncher main.go
        ;;
esac
mv main.go~ main.go

size=$(du -cs ${BUILD}/tmp | sed '1!d' | grep -oe "^[0-9]*")
sed -i "s/{{version}}/${version}/g;s/{{size}}/${size}/g;s/{{architecture}}/${architecture}/g" ${BUILD}/tmp/DEBIAN/control

fakeroot dpkg-deb -b -z9 ${BUILD}/tmp ${BUILD}/release

echo "done"
