#!/bin/sh -e

CONFIG_DIR="$HOME/.config/delauncher"

case "$1" in
    configure|reconfigure)
    	old_version="$2"
    	[ "$(echo "$old_version"|cut -c1)" = "1" ] &&
    		rm -rf "$CONFIG_DIR/delauncher.key" && \
    		cp "${CONFIG_DIR}/config.json" "${CONFIG_DIR}/config.json.backup" && \
    		rm -rf "${CONFIG_DIR}/config.json" && \
    	 	echo "Configuration removed. Backup: ${CONFIG_DIR}/config.json.backup"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
